name: CI/CD Pipeline

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: save-video-tg-bot
  IMAGE_ID: ghcr.io/tialexsey/save-video-tg-bot
  IMAGE_VERSION: Brewmaster

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: SaveFromSocialMediaTgBot/Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ env.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-on-server:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            echo "${{ secrets.SERVER_PASS }}" | sudo -S docker stop ${{ env.IMAGE_NAME }} || true
            echo "${{ secrets.SERVER_PASS }}" | sudo -S docker rm ${{ env.IMAGE_NAME }} || true
            echo "${{ secrets.SERVER_PASS }}" | sudo -S docker image prune -a -f
            echo "${{ secrets.SERVER_PASS }}" | sudo -S docker run --pull=always -d \
              --name ${{ env.IMAGE_NAME }} \
              -p 57049:57100 \
              -p 57249:57300 \
              -e TOKEN="${{ secrets.TOKEN }}" \
              -e TWITTER_TOKEN="${{ secrets.TWITTER_TOKEN }}" \
              -e RETRY_COUNT="${{ secrets.RETRY_COUNT }}" \
              -e INST_LOGIN="${{ secrets.INST_LOGIN }}" \
              -e INST_PASSWORD="${{ secrets.INST_PASSWORD }}" \
              -e INST_COOKIE_SESSION_ID="${{ secrets.INST_COOKIE_SESSION_ID }}" \
              -e REDIS_CONNECTION_STRING="${{ secrets.REDIS_CONNECTION_STRING }}" \
              -e Serilog__WriteTo__1__Args__hostnameOrAddress="${{ secrets.GRAYLOG_HOST }}" \
              ${{ env.IMAGE_ID }}:${{ env.IMAGE_VERSION }}